name = "lean20-to-statuspage"
type = "webpack"
account_id = "eabf424c4d540c6ed66594c972c265bb"
workers_dev = true
webpack_config = "webpack.config.js"

[triggers]
crons = ["* * * * *"]

[env.production]
